apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: quitafondo
spec:
  version: "v1.0.0"
  image: "erjuanpc/quitafondo-func:v1"
  imageCredentials:
    name: push-secret
  port: 8080 # default to 8080
  build:
    builder: "openfunction/gcp-builder:v1"
    env:
      GOOGLE_FUNCTION_TARGET: "quitafondo"
      GOOGLE_FUNCTION_SIGNATURE_TYPE: "http"
      GOOGLE_FUNCTION_SOURCE: "main.py"
    srcRepo:
      url: "https://github.com/JohnStopped/ImplOpenFunctionTFG.git"
      revision: "main"
  serving:
    runtime: knative # default to knative
    template:
      containers:
        - name: function # DO NOT change this
          imagePullPolicy: IfNotPresent
  route:
    gatewayRef:
      name: openfunction
      namespace: openfunction
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /quitafondo
    hostnames:
    - "sample.ofn.io"    
